const GET_FILMS = "GET_FILMS";
const GET_GENRES = "GET_GENRES";
const GET_FILM_DETAILS = "GET_FILM_DETAILS";
const DARK_MODE_TOGGLE = "DARK_MODE_TOGGLE";

export {GET_GENRES, GET_FILMS, GET_FILM_DETAILS, DARK_MODE_TOGGLE}