const bearer_token = 'eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJhOGI3NWU1MzQwZjhiN2UwMGNhNjk0YzlhZDgxMWJhNSIsInN1YiI6IjYxMmY1M2YwNmEzNDQ4MDA2MjEzMmVhNCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.lSpWwSix_cMaGeBglqUoOV_MXjwqzowkIUd9s0jzezg';

export {bearer_token}